export const MOTIVATIONAL_QUOTES = [
  "Believe you can and you're halfway there.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Don't count the days, make the days count.",
  "The future depends on what you do today.",
  "It always seems impossible until it's done.",
  "Don't wait. The time will never be just right.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Action is the foundational key to all success.",
  "Do what you can, with what you have, where you are.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Dream big and dare to fail.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Everything you've ever wanted is on the other side of fear.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The best way to predict the future is to create it.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or think you can't, you're right.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "A year from now you may wish you had started today.",
  "Don't be afraid to give up the good to go for the great.",
  "Small progress is still progress.",
  "Productivity is being able to do things that you were never able to do before.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "Focus on being productive instead of busy.",
  "Your mind is for having ideas, not holding them.",
  "The secret of getting ahead is getting started.",
  "One day or day one. You decide.",
  "Discipline is choosing between what you want now and what you want most.",
  "The successful warrior is the average man, with laser-like focus.",
  "Don't stop when you're tired. Stop when you're done.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Be so good they can't ignore you.",
  "Winners never quit and quitters never win.",
  "The power of imagination makes us infinite.",
  "Life is 10% what happens to me and 90% of how I react to it.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character.",
  "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.",
  "People who are crazy enough to think they can change the world, are the ones who do.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
  "We generate fears while we sit. We overcome them by action.",
  "Great things are not done by impulse, but by a series of small things brought together.",
  "Persistence guarantees that results are inevitable.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.",
  "Setting goals is the first step in turning the invisible into the visible."
];

export const getDailyQuote = (): string => {
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const dayIndex = Math.floor(start.getTime() / 86400000);
  return MOTIVATIONAL_QUOTES[Math.abs(dayIndex) % MOTIVATIONAL_QUOTES.length];
};
